# Generated by Django 5.0.7 on 2024-12-11 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("indicators", models.TextField()),
            ],
            options={
                "db_table": "portfolio_settings",
            },
        ),
        migrations.CreateModel(
            name="Symbols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=200)),
                ("status", models.CharField(default="1", max_length=100)),
            ],
            options={
                "db_table": "symbols",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 11, 7, 46, 17, 921000),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2024, 12, 11, 7, 46, 17, 921000),
                max_length=200,
            ),
        ),
    ]
